### ISSUE TITLE
Does it work with arduino YUN?

### ISSUE THREAD

**Issue by thelostscientist** [sparkfun/Weather_Shield#20]

**Comment by nseidle** [comment]
Yes it should. The Yun uses an ATmega32U4 as the co-processor. See the [schematic](https://www.arduino.cc/en/uploads/Main/arduino-Yun-schematic.pdf) for more information. The shield should plug in and be able to communicate with the 32U4 without issue. However, all our example code is written for the Uno and RedBoard so I'm not sure I can help with code for the Yun.
