### ISSUE TITLE
Example includes don't match library file names

### ISSUE THREAD

**Issue by ClintonKeith** [sparkfun/Weather_Shield#21]
When compiling the Weather Shield example, I noticed that the includes:
#include "MPL3115A2.h" //Pressure sensor
#include "HTU21D.h" //Humidity sensor

needed to be changed to 
#include "SparkFunMPL3115A2.h" //Pressure sensor
#include "SparkFunHTU21D.h" //Humidity sensor

Not sure which is correct (lib names or includes)

**Comment by ToniCorinne** [comment]
Sorry about that! We tried to get all the example code when updating the Arduino libraries for 1.6+. Those have been fixed in commit 6442113715a5fa2c2fe53822eba27b16542d7d89. Thanks for pointing that out.
