### ISSUE TITLE
Memory optimizations

### ISSUE THREAD

**Issue by ClintonKeith** [sparkfun/Weather_Shield#22]
I've integrated the weathershield with an Uno and Xbee using SoftSerial to communicate.  Including the Xbee and SoftSerial libraries was a challenge due to the SRAM memory useage of the example sketch.  I cleaned up a number of the memory usage problems and have others to go, but thought I'd raise the issue here for discussion before I create a pull request:
- Use flash memory whenever possible.  Convert all print strings by putting them into the F() macro.
- Reduce averaging array size.  E.g. wind averaging arrays are 120 ints in size.  They can be reduced in size, samples taken less frequently or "averages of averages" can be used.
- Use constants and defines instead of values.  "120", "199", "10" are used repeatedly throughout the code for array and iteration size.  Constants defined at the top would allow more control.

BTW: Really impressed with how quickly this shield, hardware and example came up and ran.  Good job.

**Comment by ToniCorinne** [comment]
These all sounds like great improvements. Please do issue a pull request and we'll take a look at it. Even if it doesn't necessarily work for our examples, it's a great record to have out there for other users.

**Comment by nseidle** [comment]
Hi ClintonKeith - Yes please! If you get a good sketch put together and would like to share we'd be happy to cross link. I just touched up the [hook-up guide](https://learn.sparkfun.com/tutorials/weather-shield-hookup-guide#example-firmware---basic) and created some additional, more basic sketches to get beginners up and running. If you see places to improve the basic, weather station, or GPS sketches please do so and shoot us a pull request.

If I ever touch-up my weather stations I'll use that moment to circle back and implement some of your suggestions as well. I just can't make changes to the core code without a full setup to test it on.
