### ISSUE TITLE
Error in GPS Example Code for Longitude

### ISSUE THREAD

**Issue by bboyho** [sparkfun/Weather_Shield#23]
Customer brought up an error in the SFE Forums [ https://forum.sparkfun.com/viewtopic.php?f=14&t=39246#p176148 ]. GPS example code [ https://github.com/sparkfun/Weather_Shield/blob/master/firmware/Weather_Shield_with_GPS/Weather_Shield_with_GPS.ino ] has an error in the code when printing the variable name with the variable. Instead of saying longitude=, the code says that the latitude is equal to the longitude's value on line 445:

    Serial.print(",lat=");
    Serial.print(gps.location.lat(), 6);
    Serial.print(",lat=");
    Serial.print(gps.location.lng(), 6);

It should probably say:

    Serial.print(",lat=");
    Serial.print(gps.location.lat(), 6);
    Serial.print(",lng=");
    Serial.print(gps.location.lng(), 6);

**Comment by ToniCorinne** [comment]
@bboyho if you want to change the code file and submit a pull request, I can get that pulled in.

**Comment by bboyho** [comment]
Yup, already on it @ToniCorinne . I had to file the issues first so customers can track down the issues. I have forked it and will send in a pull request with the corrections soon. =)

**Comment by bboyho** [comment]
Issue fixed in forked commit => https://github.com/bboyho/Weather_Shield/commit/d09a0d830e3668e70adf77a1f900ca0f23c9663b

**Comment by ToniCorinne** [comment]
Fixed - closing the issue.
