### ISSUE TITLE
Error in Weather_Shield_Weather_Station.ino where "windspeedmph" reads "0.0"

### ISSUE THREAD

**Issue by bboyho** [sparkfun/Weather_Shield#24]
There have been customers reporting that the variable "_windspeedmph_" is constantly reporting "0.0". This is an error in the code Weather_Shield_Weather_Station.ino [ https://github.com/sparkfun/Weather_Shield/blob/master/firmware/Weather_Shield_Weather_Station/Weather_Shield_Weather_Station.ino ].

Looking at the sequence of code, it appears that whoever originally wrote the code did not update the global variable _windspeedmph_ for the _printWeather()_ function. Line 226 was commented out in _calcWeather()_ because the function _get_wind_speed()_ was already called in the loop function. The value was saved in the local variable called _currentSpeed_ on line 178:

    //Calc the wind speed and direction every second for 120 second to get 2 minute average
    float currentSpeed = get_wind_speed();
    .
    .
    .

By saving the value from _currentSpeed_ to the global variable, the global variable _windspeedmph_ was able to update and display a value other than "0.0":

    //Calc the wind speed and direction every second for 120 second to get 2 minute average
    float currentSpeed = get_wind_speed();
    windspeedmph = currentSpeed;//update global variable for windspeed when using the printWeather() function
    .
    .
    .

**Verifying _windspeedmph_**

You can verify that the value is correct by uncommenting out lines 356-358 and removing "/*" and "*/":

    /* Serial.println();
    Serial.print("Windspeed:");
    Serial.println(windSpeed);*/

Keep in mind that the the value printed in _calcWeather()_ outputs to the nearest hundredth while _printWeather()_ outputs to the nearest tenth. This is due to the way _serial.print()_ is called [ https://www.arduino.cc/en/Serial/Print ] . The default has the Arduino print to two decimal places. In _printWeather()_, the code specifies printing to the one decimal place.

**Comment by bboyho** [comment]
Issue fixed in forked commit => https://github.com/bboyho/Weather_Shield/commit/d09a0d830e3668e70adf77a1f900ca0f23c9663b

**Comment by ToniCorinne** [comment]
Fixed - closing the issue.
