### ISSUE TITLE
v12 checklist issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Weather_Shield#26]
(1) Per the standard, it would be nice if the "STAT1" and "STAT2" nets had a bend in them so that the flag could come straight out from the net while reading horizontally.

(2) Most parts have no PROD_ID

(3) The design loaded with an old DRC, and running the a new DRC results in errors

(4) There are air-wires in the design

(5) BRD contains Proportional text

**Comment by JoelEB** [comment]
1) Adding bends for flags
2) Updated all parts to latest and added PROD_IDs to parts without. 
3) Check board against newest DRC
4) Air-wires have been fixed
5) Text on BRD and SCH has been changed to vector.
