### ISSUE TITLE
Weather shield not working on Arduino Uno WIFI Rev 2

### ISSUE THREAD

**Issue by skuske** [sparkfun/Weather_Shield#31]
All examples work fine on an Arduino Uno, but **they are not working** on an Arduino Uno WIFI Rev 2 - a lot of errors are produced when I try to upload any of the examples:

![Bildschirmfoto 2019-03-14 um 17 40 20](https://user-images.githubusercontent.com/12996815/54374867-4e01a680-4680-11e9-849d-e6844107ad3f.png)

**Comment by tkeifer** [comment]
Any updates on this? I'm running into the same issues. (negative values on Temperature/Pressure and can't include the Si7021 library without running into the same compile errors above)

Example code from the Sparkfun MPL3115A2 library
`Pressure(Pa): -31265 Temp(f): -1766.20
Pressure(Pa): -31204 Temp(f): -1766.20
Pressure(Pa): -31148 Temp(f): -1766.20
Pressure(Pa): -31333 Temp(f): -1766.20
Pressure(Pa): -31325 Temp(f): -1766.20
Pressure(Pa): -31434 Temp(f): -1766.20`

This is the 3rd WIFI companion board I've used with no luck...

**Comment by skuske** [comment]
I am wondering if anybody of sparkfun monitors the issues... I doubt they do. Bad service.

**Comment by tkeifer** [comment]
I've had a little better luck over at their forums: https://forum.sparkfun.com/

...but yeah, it seems like the way they have this shield setup it only is really designed to work with their Photon boards. Pretty disappointed with them as well.

**Comment by santaimpersonator** [comment]
@skuske Sorry, we have a lot of repos that we curate; not including our forums, product pages, hookup guides, and etc.

I am marking this a duplicate and closing this issue since it isn't related to the hardware and there is another issue already file for the library causing the compilation issue (see https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library/issues/4). This is was my response regarding this issue:

> Unfortunately, this seems like a compatibility issue. The WiFi Rev 2 uses the AVR mega Arduino core, where the TwoWire library is causing the compilation error. Based on the library example, it was developed with the following specifications:
> 
> > Development environment specifics:
> > * IDE: Particle Dev
> > * Hardware Platform: SparkFun RedBoard
> >   * Arduino IDE 1.6.5
> 
> I'll try to bring this up to the engineering team, but this may end up being something that is out of our hands if the TwoWire library is incompatible with the sensor operation.
