### ISSUE TITLE
Commented line #234 prevents working with GPS in Weather_Shield_with_GPS_V12.ino

### ISSUE THREAD

**Issue by wittend** [sparkfun/Weather_Shield#32]
The fact that line #234 is commented out at the end of loop() prevents firmwareWeather_Shield_with_GPS_V12.ino from reading GPS if attached.  This problem is present in both the repo code and the code embedded in the tutorial page "Arduino Weather Shield Hookup Guide V12".

Uncommenting this line seems to fix things, at least with the specified GPS.

**Comment by santaimpersonator** [comment]
Closing, as this is no longer relavent to the new code implementation
