### ISSUE TITLE
Getting wrong readings

### ISSUE THREAD

**Issue by vdenduluri** [sparkfun/Weather_Shield#34]
Hi,

I connected the [weather shield](https://www.sparkfun.com/products/13956) to [sparkfun redboard plus](https://www.sparkfun.com/products/18158) and ran the example program "Weather_Shield_Basic_V12". I am getting incorrect readings. 

Is there something that I should do first before executing the program or something wrong with hardware? Anyhelp would be appreciated.

Humidity = -5.81%, temp_h = -51.85F, Pressure = -999.00Pa, temp_p = -1766.20F, light_lvl = 2.14V, VinPin = 12.08V
Humidity = -5.81%, temp_h = -51.85F, Pressure = -999.00Pa, temp_p = -1766.20F, light_lvl = 2.19V, VinPin = 11.91V
Humidity = -5.81%, temp_h = -51.85F, Pressure = -999.00Pa, temp_p = -1766.20F, light_lvl = 2.19V, VinPin = 12.08V
Humidity = -5.81%, temp_h = -51.85F, Pressure = -999.00Pa, temp_p = -1766.20F, light_lvl = 2.08V, VinPin = 12.90V

Thanks.

**Comment by santaimpersonator** [comment]
Based upon the VinPin reading, make sure you are connecting an appropriate backup battery as defined in the schematic:
![image](https://github.com/sparkfun/Weather_Shield/assets/36016723/1219feaf-bfbe-428d-9776-7a380c6efb27)

_If you are still running into issues, please use our [forum](https://forum.sparkfun.com/) to submit a post for some [technical assistance](https://www.sparkfun.com/technical_assistance)._

**Comment by santaimpersonator** [comment]
No response; closing issue.
